### ISSUE TITLE
Abundance Calculations

### ISSUE THREAD

**Issue by lemointm** [alexmalins/radioactivedecay#30]
Hi Alex! My name is Thom, and I am an undergraduate physics researcher working with the TARDIS SN collaboration to simulate supernova explosions. Thanks for sharing your code! I was curious if you had any plans to incorporate abundance calculations into the code, as we have been searching for an alternative to the PyNE package that would calculate the abundance of decay products after a decay period. Feel free to check out our page at: https://tardis-sn.github.io/tardis/index.html Thanks!

**Comment by alexmalins** [comment]
Hi Thom, thanks for creating an issue for this idea. I had a look at the TARDIS source code (tardis.io.decay) and it currently uses PyNE's Material class for decay calculations, right? Substituting radioactivedecay in there would require three things of it which it currently does not do:

- conversion between activity and number of radionuclides (A=λN)
- keeping track of the number of stable nuclides (counting in what is formed from radioactive decay over time)
- adding atomic mass data to convert between number of nuclides (or moles) and mass

Adding these in is technically not so difficult. But first may I ask why you are searching for an alternative to PyNE? Is to do with bugs in PyNE's decay solver, or some other reason?

Attempting to fix PyNE's decay solver has been on my mind for a while. And it might be a more efficient use of time and effort to do that rather than duplicating functionality from PyNE's Material class in radioactivedecay.

**Comment by wkerzendorf** [comment]
Hi - Pyne has relatively complex dependencies and requires c binding for building. That often limits numpy and scipy versions.

**Comment by lemointm** [comment]
Hi Alex, I've been working on an abundance solver, and currently I have a separate parser I've been designing to take the [AME2020 atomic data](https://www-nds.iaea.org/amdc/ame2020/mass_1.mas20.txt), which I have a [jupyter notebook version](https://gist.github.com/lemointm/98ad17e7466d91acfc9abf40b972dae7) of (still in development :)). I was hoping to add this to your code along with the abundance solver. Before I make a pull request, I was hoping to hear what your ideas were about file locations. I was hoping to add the parser and abundance solver as a module for `radioactivedecay` and want to make sure it fits your guidelines for format and file location.

**Comment by alexmalins** [comment]
Thom, thanks again for your support on this. I dropped some comments in answer to your Qs over on the TARDIS slack channel.

**Comment by alexmalins** [comment]
Closing this off now - the latest release (v0.4.2) now incorporates all the functionality discussed!
