### ISSUE TITLE
JOSS Paper: Minor edits to the paper

### ISSUE THREAD

**Issue by munkm** [alexmalins/radioactivedecay#37]
Hi, 

I'm reviewing this tool for JOSS in https://github.com/openjournals/joss-reviews/issues/3318 and I have a few minor suggestions that I think would improve the paper:

- [x] add citations to PyNE and Radiological toolbox on line 25. You have them later but this is their first appearance in the manuscript
- [x] on l86 you mention fig1a is based on NetworkX and l91 is based on Matplotlib, but I think it would be clearer if you said it is made using those tools. 
- [x] I do not believe PyNE can create decay diagrams like fig 1a, so you could add that feature to your statement of need section too. They're very nice. 
- [x] It might be worth explicitly stating that all of this is based on atomic fractions and not mass fractions of the nuclear materials, unless there's an option for that that I missed in the documentation. This isn't necessary for the JOSS publication though

**Comment by alexmalins** [comment]
Hi @munkm,

Thanks for these suggestions and ideas. Over on the [joss_paper](https://github.com/alexmalins/radioactivedecay/tree/joss_paper) branch I committed changes in line with the first two suggestions.

Item 3: Actually when I was developing this function I stumbled across this [script](https://github.com/pyne/pyne/blob/9c1d41237dc26597cd2463d5968d2ab4e2cfce0f/pyne/gui/decaychain.py) in the PyNE repository which appears to create decay diagrams using Graphviz. I've not tried it - it doesn't appear to be documented anywhere and I'm not sure if it is supported. However given it exists and because Radiological Toolbox can plot similar diagrams, I didn't feel this was a sufficiently distinguishing feature to add to the statement of need in the radioactivedecay JoSS paper.

Item 4: All of this is based on activity / activity fractions in the version that was entered for review (v0.3.2). As it happens, a student (Thom Lemoine - @lemointm) who has been working on [TARDIS](https://github.com/tardis-sn/tardis) & radioactivedecay over summer has coded new functionality so radioactivedecay supports mass, mass fractions, moles, number of atoms & number fractions. This is all now working over on the [devel](https://github.com/alexmalins/radioactivedecay/tree/devel) branch, and we're close to cutting a new release. Instead of stating this limitation of the old version, I was wondering if there was a way to add Thom as a co-author to the paper so a) he can get credit for this good work, and b) the JoSS paper is up to date with the latest functionality?

**Comment by munkm** [comment]
I think if you cut a new release and update the paper with Thom as a co-author items 3 and 4 should be resolved by that. I have no issues with us closing this issue if that's the plan to move forward. 🙂

**Comment by alexmalins** [comment]
Hi @munkm,

Yep, that's the plan. The v0.4 release added the new mass and mole fractions functionality. We're just in the process of updating the paper and adding Thom as a new co-author. Please bear with us, will update and close off this issue once done.

**Comment by munkm** [comment]
Oh, not a problem at all! It's great you've got some rad new features. 🙂

**Comment by alexmalins** [comment]
Ok, all is ready now. PR #42 updated the paper to the joss_paper branch. Thanks for your helpful suggestions, @munkm !
